In [ ]:
<a href="https://colab.research.google.com/github/hiddouche/CNN_NSL_KDD/blob/master/NSL_KDD_Final.ipynb"  target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [35]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 


import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from joblib import dump, load
from sklearn.metrics import accuracy_score, f1_score, precision_score,recall_score
from sklearn.linear_model import Perceptron
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import AdaBoostClassifier
import matplotlib.pyplot as plt

from sklearn import svm, datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.utils.multiclass import unique_labels
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from scipy import interp
from itertools import cycle
import seaborn as sns
from sklearn.datasets import make_classification
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
import sklearn.metrics as metrics

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

In [36]:
import pandas as pd
import numpy as np
import sys
import keras
import sklearn
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Embedding
from keras.layers import LSTM, SimpleRNN, GRU, Bidirectional, BatchNormalization,Convolution1D,MaxPooling1D, Reshape, GlobalAveragePooling1D
from keras.utils import to_categorical
import sklearn.preprocessing
from sklearn import metrics
from scipy.stats import zscore
from tensorflow.keras.utils import get_file, plot_model
from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import EarlyStopping
import matplotlib.pyplot as plt
print(pd.__version__)
print(np.__version__)
print(sys.version)
print(sklearn.__version__)


1.0.4
1.18.5
3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]
0.22.2.post1


In [37]:
#Loading training set into dataframe
 
df = pd.read_csv('/content/drive/My Drive/datasets/KDDTrain+.txt', header=None)
df.head()

0    1         2   3    4     5   ...    37    38    39    40       41  42
0   0  tcp  ftp_data  SF  491     0  ...  0.00  0.00  0.05  0.00   normal  20
1   0  udp     other  SF  146     0  ...  0.00  0.00  0.00  0.00   normal  15
2   0  tcp   private  S0    0     0  ...  1.00  1.00  0.00  0.00  neptune  19
3   0  tcp      http  SF  232  8153  ...  0.03  0.01  0.00  0.01   normal  21
4   0  tcp      http  SF  199   420  ...  0.00  0.00  0.00  0.00   normal  21

[5 rows x 43 columns]

In [38]:
#Loading testing set into dataframe
qp = pd.read_csv('/content/drive/My Drive/datasets/KDDTest+.txt', header=None)
qp.head()

0     1         2     3      4   5   ...   37   38    39    40       41  42
0   0   tcp   private   REJ      0   0  ...  0.0  0.0  1.00  1.00  neptune  21
1   0   tcp   private   REJ      0   0  ...  0.0  0.0  1.00  1.00  neptune  21
2   2   tcp  ftp_data    SF  12983   0  ...  0.0  0.0  0.00  0.00   normal  21
3   0  icmp     eco_i    SF     20   0  ...  0.0  0.0  0.00  0.00    saint  15
4   1   tcp    telnet  RSTO      0  15  ...  0.0  0.0  0.83  0.71    mscan  11

[5 rows x 43 columns]

In [39]:
#Reset column names for training set
df.columns = ['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
'num_access_files', 'num_outbound_cmds', 'is_host_login',
'is_guest_login', 'count', 'srv_count', 'serror_rate',
'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
'dst_host_srv_count', 'dst_host_same_srv_rate','dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
'dst_host_srv_rerror_rate', 'subclass', 'difficulty_level']
df.head()


duration protocol_type  ... subclass difficulty_level
0         0           tcp  ...   normal               20
1         0           udp  ...   normal               15
2         0           tcp  ...  neptune               19
3         0           tcp  ...   normal               21
4         0           tcp  ...   normal               21

[5 rows x 43 columns]

In [40]:
#Reset column names for testing set
qp.columns = ['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
'num_access_files', 'num_outbound_cmds', 'is_host_login',
'is_guest_login', 'count', 'srv_count', 'serror_rate',
'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
'dst_host_srv_count', 'dst_host_same_srv_rate','dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
'dst_host_srv_rerror_rate', 'subclass', 'difficulty_level']
qp.head()

duration protocol_type  ... subclass difficulty_level
0         0           tcp  ...  neptune               21
1         0           tcp  ...  neptune               21
2         2           tcp  ...   normal               21
3         0          icmp  ...    saint               15
4         1           tcp  ...    mscan               11

[5 rows x 43 columns]

In [41]:
#accessing names of training columns
lst_names = df.columns # returns a list of column names
lst_names


Index(['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
       'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
       'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
       'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
       'num_access_files', 'num_outbound_cmds', 'is_host_login',
       'is_guest_login', 'count', 'srv_count', 'serror_rate',
       'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
       'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
       'dst_host_srv_count', 'dst_host_same_srv_rate',
       'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
       'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
       'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
       'dst_host_srv_rerror_rate', 'subclass', 'difficulty_level'],
      dtype='object')

In [42]:
#accessing names of testing columns
testlst_names = qp.columns
testlst_names

Index(['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
       'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
       'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
       'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
       'num_access_files', 'num_outbound_cmds', 'is_host_login',
       'is_guest_login', 'count', 'srv_count', 'serror_rate',
       'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
       'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
       'dst_host_srv_count', 'dst_host_same_srv_rate',
       'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
       'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
       'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
       'dst_host_srv_rerror_rate', 'subclass', 'difficulty_level'],
      dtype='object')

In [43]:
#Dropping the last columns of training set
df = df.drop('difficulty_level', 1) # we don't need it in this project
df.shape

(125973, 42)

In [44]:
#Dropping the last columns of testing set
qp = qp.drop('difficulty_level', 1)
qp.shape

(22544, 42)

In [45]:
df.isnull().values.any()

False

In [46]:
qp.isnull().values.any()

False

In [47]:
#defining col list
cols = ['protocol_type','service','flag']
cols

['protocol_type', 'service', 'flag']

In [48]:
#One-hot encoding
def one_hot(df, cols):
    """
    @param df pandas DataFrame
    @param cols a list of columns to encode
    @return a DataFrame with one-hot encoding
    """
    for each in cols:
        dummies = pd.get_dummies(df[each], prefix=each, drop_first=False)
        df = pd.concat([df, dummies], axis=1)
        df = df.drop(each, 1)
    return df


In [49]:
#Merging train and test data
combined_data = pd.concat([df,qp])

In [50]:
#Applying one hot encoding to combined data
combined_data = one_hot(combined_data,cols)

In [51]:
#Function to min-max normalize
def normalize(df, cols):
    """
    @param df pandas DataFrame
    @param cols a list of columns to encode
    @return a DataFrame with normalized specified features
    """
    result = df.copy() # do not touch the original df
    for feature_name in cols:
        max_value = df[feature_name].max()
        min_value = df[feature_name].min()
        if max_value > min_value:
            result[feature_name] = (df[feature_name] - min_value) / (max_value - min_value)
    return result

In [52]:
#Dropping subclass column for training set
tmp = combined_data.pop('subclass')

In [53]:
#Normalizing training set
new_train_df = normalize(combined_data,combined_data.columns)
new_train_df

duration     src_bytes     dst_bytes  ...  flag_S3  flag_SF  flag_SH
0           0.0  3.558064e-07  0.000000e+00  ...      0.0      1.0      0.0
1           0.0  1.057999e-07  0.000000e+00  ...      0.0      1.0      0.0
2           0.0  0.000000e+00  0.000000e+00  ...      0.0      0.0      0.0
3           0.0  1.681203e-07  6.223962e-06  ...      0.0      1.0      0.0
4           0.0  1.442067e-07  3.206260e-07  ...      0.0      1.0      0.0
...         ...           ...           ...  ...      ...      ...      ...
22539       0.0  5.753774e-07  2.542106e-07  ...      0.0      1.0      0.0
22540       0.0  2.297162e-07  7.160648e-07  ...      0.0      1.0      0.0
22541       0.0  3.952277e-05  6.346868e-06  ...      0.0      1.0      0.0
22542       0.0  3.043558e-08  3.206260e-08  ...      0.0      1.0      0.0
22543       0.0  0.000000e+00  0.000000e+00  ...      0.0      0.0      0.0

[148517 rows x 122 columns]

In [54]:
#Fixing labels for training set
classlist = []
check1 = ("apache2","back","land","neptune","mailbomb","pod","processtable","smurf","teardrop","udpstorm","worm")
check2 = ("ipsweep","mscan","nmap","portsweep","saint","satan")
check3 = ("buffer_overflow","loadmodule","perl","ps","rootkit","sqlattack","xterm")
check4 = ("ftp_write","guess_passwd","httptunnel","imap","multihop","named","phf","sendmail","Snmpgetattack","spy","snmpguess","warezclient","warezmaster","xlock","xsnoop")

DoSCount=0
ProbeCount=0
U2RCount=0
R2LCount=0
NormalCount=0

for item in tmp:
    if item in check1:
        classlist.append("DoS")
        DoSCount=DoSCount+1
    elif item in check2:
        classlist.append("Probe")
        ProbeCount=ProbeCount+1
    elif item in check3:
        classlist.append("U2R")
        U2RCount=U2RCount+1
    elif item in check4:
        classlist.append("R2L")
        R2LCount=R2LCount+1
    else:
        classlist.append("Normal")
        NormalCount=NormalCount+1   

In [55]:
DoSCount

53387

In [56]:
#Appending class column to training set
new_train_df["Class"] = classlist
new_train_df

duration     src_bytes     dst_bytes  ...  flag_SF  flag_SH   Class
0           0.0  3.558064e-07  0.000000e+00  ...      1.0      0.0  Normal
1           0.0  1.057999e-07  0.000000e+00  ...      1.0      0.0  Normal
2           0.0  0.000000e+00  0.000000e+00  ...      0.0      0.0     DoS
3           0.0  1.681203e-07  6.223962e-06  ...      1.0      0.0  Normal
4           0.0  1.442067e-07  3.206260e-07  ...      1.0      0.0  Normal
...         ...           ...           ...  ...      ...      ...     ...
22539       0.0  5.753774e-07  2.542106e-07  ...      1.0      0.0  Normal
22540       0.0  2.297162e-07  7.160648e-07  ...      1.0      0.0  Normal
22541       0.0  3.952277e-05  6.346868e-06  ...      1.0      0.0     DoS
22542       0.0  3.043558e-08  3.206260e-08  ...      1.0      0.0  Normal
22543       0.0  0.000000e+00  0.000000e+00  ...      0.0      0.0   Probe

[148517 rows x 123 columns]

In [57]:
new_train_df["Class"].value_counts()

Normal    77232
DoS       53387
Probe     14077
R2L        3702
U2R         119
Name: Class, dtype: int64

In [58]:
new_train_df.isnull().values.any()

False

In [59]:
y_train=new_train_df["Class"]
y_train

0        Normal
1        Normal
2           DoS
3        Normal
4        Normal
          ...  
22539    Normal
22540    Normal
22541       DoS
22542    Normal
22543     Probe
Name: Class, Length: 148517, dtype: object

In [60]:
y_train.isnull().values.any()

False

In [61]:
combined_data_X = new_train_df.drop('Class', 1)
combined_data_X

duration     src_bytes     dst_bytes  ...  flag_S3  flag_SF  flag_SH
0           0.0  3.558064e-07  0.000000e+00  ...      0.0      1.0      0.0
1           0.0  1.057999e-07  0.000000e+00  ...      0.0      1.0      0.0
2           0.0  0.000000e+00  0.000000e+00  ...      0.0      0.0      0.0
3           0.0  1.681203e-07  6.223962e-06  ...      0.0      1.0      0.0
4           0.0  1.442067e-07  3.206260e-07  ...      0.0      1.0      0.0
...         ...           ...           ...  ...      ...      ...      ...
22539       0.0  5.753774e-07  2.542106e-07  ...      0.0      1.0      0.0
22540       0.0  2.297162e-07  7.160648e-07  ...      0.0      1.0      0.0
22541       0.0  3.952277e-05  6.346868e-06  ...      0.0      1.0      0.0
22542       0.0  3.043558e-08  3.206260e-08  ...      0.0      1.0      0.0
22543       0.0  0.000000e+00  0.000000e+00  ...      0.0      0.0      0.0

[148517 rows x 122 columns]

In [62]:
oos_pred = []

In [63]:
from sklearn.model_selection import StratifiedKFold

In [64]:
kfold = StratifiedKFold(n_splits=6,shuffle=True,random_state=42)
kfold.get_n_splits(combined_data_X,y_train)

6

In [65]:
    #Bidirectional RNN
    batch_size = 32
    model = Sequential()
    model.add(Convolution1D(64, kernel_size=122, border_mode="same",activation="relu",input_shape=(122, 1)))
    model.add(MaxPooling1D(pool_length=(5)))
    model.add(BatchNormalization())
    model.add(Bidirectional(LSTM(64, return_sequences=False))) 
    model.add(Reshape((128, 1), input_shape = (128, )))
    
    model.add(MaxPooling1D(pool_length=(5)))
    model.add(BatchNormalization())
    model.add(Bidirectional(LSTM(128, return_sequences=False))) 
    
    model.add(Dropout(0.5))
    model.add(Dense(5))
    model.add(Activation('softmax'))
    model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(64, kernel_size=122, activation="relu", input_shape=(122, 1), padding="same")`
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: UserWarning: Update your `MaxPooling1D` call to the Keras 2 API: `MaxPooling1D(pool_size=5)`
  """
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: UserWarning: Update your `MaxPooling1D` call to the Keras 2 API: `MaxPooling1D(pool_size=5)`
  # Remove the CWD from sys.path while we load stuff.


In [66]:
for layer in model.layers:
    print(layer.output_shape)

(None, 122, 64)
(None, 24, 64)
(None, 24, 64)
(None, 128)
(None, 128, 1)
(None, 25, 1)
(None, 25, 1)
(None, 256)
(None, 256)
(None, 5)
(None, 5)


In [67]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_2 (Conv1D)            (None, 122, 64)           7872      
_________________________________________________________________
max_pooling1d_3 (MaxPooling1 (None, 24, 64)            0         
_________________________________________________________________
batch_normalization_3 (Batch (None, 24, 64)            256       
_________________________________________________________________
bidirectional_3 (Bidirection (None, 128)               66048     
_________________________________________________________________
reshape_2 (Reshape)          (None, 128, 1)            0         
_________________________________________________________________
max_pooling1d_4 (MaxPooling1 (None, 25, 1)             0         
_________________________________________________________________
batch_normalization_4 (Batch (None, 25, 1)            

In [68]:
for train_index, test_index in kfold.split(combined_data_X,y_train):
    train_X, test_X = combined_data_X.iloc[train_index], combined_data_X.iloc[test_index]
    train_y, test_y = y_train.iloc[train_index], y_train.iloc[test_index]
    
    print("train index:",train_index)
    print("test index:",test_index)
    
    x_columns_train = new_train_df.columns.drop('Class')
    x_train_array = train_X[x_columns_train].values
    x_train_1=np.reshape(x_train_array, (x_train_array.shape[0], x_train_array.shape[1], 1))
    
    dummies = pd.get_dummies(train_y) # Classification
    outcomes = dummies.columns
    num_classes = len(outcomes)
    y_train_1 = dummies.values
    
    x_columns_test = new_train_df.columns.drop('Class')
    x_test_array = test_X[x_columns_test].values
    x_test_2=np.reshape(x_test_array, (x_test_array.shape[0], x_test_array.shape[1], 1))
    
    dummies_test = pd.get_dummies(test_y) # Classification
    outcomes_test = dummies_test.columns
    num_classes = len(outcomes_test)
    y_test_2 = dummies_test.values
    
   
    model.fit(x_train_1, y_train_1,validation_data=(x_test_2,y_test_2), epochs=10)
    
    pred = model.predict(x_test_2)
    pred = np.argmax(pred,axis=1)
    y_eval = np.argmax(y_test_2,axis=1)
    score = metrics.accuracy_score(y_eval, pred)
    oos_pred.append(score)
    print("Validation score: {}".format(score))

train index: [     0      2      3 ... 148514 148515 148516]
test index: [     1      7     15 ... 148506 148511 148513]
Train on 123764 samples, validate on 24753 samples
Epoch 1/10
123764/123764 [==============================] - 374s 3ms/step - loss: 0.1135 - accuracy: 0.9649 - val_loss: 0.0638 - val_accuracy: 0.9784
Epoch 2/10
123764/123764 [==============================] - 373s 3ms/step - loss: 0.0684 - accuracy: 0.9766 - val_loss: 0.0487 - val_accuracy: 0.9823
Epoch 3/10
123764/123764 [==============================] - 367s 3ms/step - loss: 0.0518 - accuracy: 0.9819 - val_loss: 0.0578 - val_accuracy: 0.9810
Epoch 4/10
123764/123764 [==============================] - 366s 3ms/step - loss: 0.0440 - accuracy: 0.9850 - val_loss: 0.0391 - val_accuracy: 0.9861
Epoch 5/10
123764/123764 [==============================] - 369s 3ms/step - loss: 0.0393 - accuracy: 0.9864 - val_loss: 0.0332 - val_accuracy: 0.9888
Epoch 6/10
123764/123764 [==============================] - 368s 3ms/step - lo

In [69]:
oos_pred

[0.9903446046943805,
 0.9919605704359068,
 0.9912737849957581,
 0.9923241627277501,
 0.9929301498808225,
 0.9933338720103426]

In [70]:
dummies_test.columns

Index(['DoS', 'Normal', 'Probe', 'R2L', 'U2R'], dtype='object')

In [71]:
test_y.value_counts()

Normal    12872
DoS        8897
Probe      2347
R2L         617
U2R          19
Name: Class, dtype: int64

In [72]:
from sklearn.metrics import confusion_matrix

In [73]:
cm = confusion_matrix(y_eval, pred, labels=[0,1,2,3,4])

In [74]:
print(cm)

[[ 8881    13     3     0     0]
 [    8 12829    19    15     1]
 [    0    15  2330     2     0]
 [    0    78     1   537     1]
 [    0     5     1     3    10]]


In [78]:
tp = 0
for i in range(5):
  for j in range(5):
    if i == j:
      tp = tp + cm[i][j]
tp_rate = (tp/24752)*100

print("True Positive Rate: " + str(tp_rate))

True Positive Rate: 99.33338720103426


In [79]:
dr = (cm[0][0] + cm[2][2] + + cm[3][3] + + cm[4][4])/(8897+2347+617+19)
print("Detection Rate: " + str(dr))

Detection Rate: 0.9897306397306397
